backend:
  name: github
  repo: coopsben0-debug/B-T-Collectibles
  branch: main

# Saves images directly into your GitHub repo folder structure
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "art"
    label: "Art"
    folder: "content/art"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Image", name: "image", widget: "image"}
  - name: "crafts"
    label: "Crafts"
    folder: "content/crafts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Image", name: "image", widget: "image"}
  - name: "hobbies"
    label: "Hobbies"
    folder: "content/hobbies"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Image", name: "image", widget: "image"}
