backend:
  name: github
  repo: coopsben0-debug/B-T-Collectibles
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "art"
    label: "Art"
    folder: "products/art"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "number", value_type: "float", step: 0.01}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - {label: "B.A. Cooper Signature", value: "B.A. Cooper Signature"}
          - {label: "T.L. Ku Signature", value: "T.L. Ku Signature"}
          - {label: "Wood Work", value: "Wood Work"}
          - {label: "Miniature", value: "Miniature"}
          - {label: "Stone", value: "Stone"}
